### ISSUE TITLE
`wait_still_screen` before `assert_screen` should not be necessary

### ISSUE THREAD

**Issue by okurz** [profanity-im/openqa-profanity-testsuite#1]
In https://github.com/profanity-im/openqa-profanity-testsuite/blob/de8528e8e28a52f504708bdd053f32dae820a8bc/tests/profanity.pm#L26 but also in other examples a call to `wait_still_screen` is done *before* in the next line there is `assert_screen`. While this certainly workers with the right choice of a needle should not be necessary. Think of it as a user would do: A user would not stare at his watch to see if at least 10 seconds have passed before looking for something specific on the screen: The user would just wait for a *specific* screen to show up :)

**Comment by jubalh** [comment]
Thanks for checking! :)
